### ISSUE TITLE
关于repeats

### ISSUE THREAD

**Issue by yangchenlarkin** [Joeyqiushi/JX_GCDTimer#1]
[JX_GCDTimerManager scheduledDispatchTimerWithName: timeInterval: queue: repeats: actionOption: action:];

这个接口中的repeats参数可以替换成 repeatsCount:(NSUInterger)count，0表示无限重复，大于0表示重复次数。

**Comment by Joeyqiushi** [comment]
是的，可以根据你具体的使用场景来修改这个工具。我们项目中暂时没有这种需求。
