### ISSUE TITLE
不能操作UI主线程刷新

### ISSUE THREAD

**Issue by hanq** [Joeyqiushi/JX_GCDTimer#3]
RT：不能操作UI主线程刷新，建议在61行的代码替换为：
            dispatch_source_set_event_handler(timer, ^{
                dispatch_async(dispatch_queue_create(0, 0), ^{
                    dispatch_async(dispatch_get_main_queue(), ^{
                        action();
                    });
                });

**Comment by Joeyqiushi** [comment]
UI操作的主线程刷新，应该放在UI处理的部分。放在这里会强制所有使用timer的地方都在主线程。另外，参数queue你也可以传入dispatch_get_main_queue()以保证任务在主线程得到执行。
